version: "2"

services:
    jenkins_master:
        image: jenkins:2.0-beta-1
        networks:
            - jenkins
        ports:
            - "8080:8080/tcp"
            - "50000:50000/tcp"
        container_name: jenkins_master
        volumes:
             - jenkins:${JENKINS_HOME}

networks:
    jenkins:
        driver: overlay
volumes:
    jenkins:
        driver: flocker
