version: "2"

services:
    jenkins:
        image: jenkins:2.0-beta-1
        networks:
            - jenkins
        ports:
            - "8080:8080/tcp"
        volumes:
             - jenkins:${JENKINS_HOME}

networks:
    jenkins:
        driver: overlay
volumes:
    jenkins:
        driver: flocker
